---
title: "People-centric restoration: Comparing district level biophysical potential with the people-centric restoration potential"
author: "Pooja Choksi"
date: '2022-06-24'
output: html_document
---

```{r setup, include=FALSE}

library(data.table)
library(dplyr)
library(tidyr)
library(sf)
library(rgdal)
library(raster)
library(tools)
library(sp)
library(ggplot2)
```

READ IN ALL THE RASTERS FROM THE BIOPHYSICAL POTENTIAL STUDIES AND DISTRICT SHAPEFILE FROM PREVIOUS CODE

```{r message=TRUE, warning=TRUE, include=TRUE}

#rasters for three studies we're comparing our scale with
brancalion <- raster("C:\\Users\\pooja\\Documents\\GitHub\\Land-Tenure-Restoration-Potential\\Land-Tenure-Restoration-Potential\\Restoration_Potential_Studies\\India_Clipped\\Brancalion_India_Clipped.tif")

strassburg = raster("C:\\Users\\pooja\\Documents\\GitHub\\Land-Tenure-Restoration-Potential\\Land-Tenure-Restoration-Potential\\Restoration_Potential_Studies\\India_Clipped\\Strassburg_india_Clipped.tif")

strassburg_biodiversity_climate = raster("C:\\Users\\pooja\\Documents\\GitHub\\Land-Tenure-Restoration-Potential\\Land-Tenure-Restoration-Potential\\Restoration_Potential_Studies\\Strassburg_et_al_2020\\scen_cb-bd_gradient.tif")

wri = raster("C:\\Users\\pooja\\Documents\\GitHub\\Land-Tenure-Restoration-Potential\\Land-Tenure-Restoration-Potential\\Restoration_Potential_Studies\\India_Clipped\\Potapov_India_Clipped.tif")

#district shapefile with info on the people-centric variables
districts = readOGR("C:\\Users\\pooja\\Documents\\GitHub\\Land-Tenure-Restoration-Potential\\Land-Tenure-Restoration-Potential\\Census2011-District-Shapefiles\\District-MPI-Merged-593districts.shp")
  
```

EXTRACT MEAN BIOPHYSICAL POTENTIAL FOR EACH DISTRICT AND RANK DISTRICTS ACCORDING TO BIOPHYSICAL POTENTIAL

```{r message=FALSE, warning=FALSE, include=TRUE}

#extract mean or majority (for wri data) of raster for each district
brancalion_extracted = raster::extract(brancalion, districts, fun = mean, na.rm = T, small = T, sp=TRUE)
brancalion_extracted_df <- as(brancalion_extracted, "data.frame")

strassburg_extracted = raster::extract(strassburg, districts, fun = mean, na.rm = T, small = T, sp=TRUE)
strassburg_extracted_df <- as(strassburg_extracted, "data.frame")

strassburg_blioclim_extracted = raster::extract(strassburg_biodiversity_climate, districts, fun = mean, na.rm = T, small = T, sp=TRUE)
strassburg_blioclim_extracted_df <- as(strassburg_blioclim_extracted, "data.frame")

wri_extracted = raster::extract(wri, districts, fun= modal, na.rm = T, small= T, sp=TRUE)
wri_extracted_df <- as(wri_extracted, "data.frame")

potential_extracted = strassburg_extracted_df

#combine the data of extracted values 
potential_extracted = merge(brancalion_extracted_df, strassburg_extracted_df[c("Strassburg_India_Clipped", "NAME_1", "NAME_2")], by.x = c("NAME_2", "NAME_1"), by.y =c("NAME_2", "NAME_1"))
                            
#combine the data of extracted values 
potential_extracted = merge(potential_extracted, wri_extracted_df[c("Potapov_India_Clipped", "NAME_2", "NAME_1")], by.x = c("NAME_2", "NAME_1"), by.y =c("NAME_2", "NAME_1"))

#remove the districts which don't have a value for climate vulnerability from the larger districts file and potential extracted
potential_extracted= potential_extracted[!is.na(potential_extracted$Pp__M),]

#rank the districts as per their biophysical potential 
#1. Brancalion
#reorder the districts in descending order of MPI
potential_extracted  <- potential_extracted [order(potential_extracted$Brancalion_India_Clipped, decreasing=TRUE),]

#assign each district a rank
potential_extracted= potential_extracted%>% mutate(branca_rank = match(Brancalion_India_Clipped, unique(Brancalion_India_Clipped)))

#2. Potapov:
#reorder the districts in descending order of MPI
potential_extracted  <- potential_extracted [order(potential_extracted$Potapov_India_Clipped, decreasing=TRUE),]

#assign each district a rank
potential_extracted= potential_extracted%>% mutate(wri_rank = match(Potapov_India_Clipped, unique(Potapov_India_Clipped)))

#3. Strassburg
#scale the strassburg potential % from 0 to 1 
#Create a scale of 0 to 1
range01 <- function(x){((x-min(x))/(max(x)-min(x)))}

potential_extracted  <- potential_extracted [order(potential_extracted$Strassburg_India_Clipped, decreasing=FALSE),]

potential_extracted$Strassburg_Scaled = range01(potential_extracted$scen_cb.bd_gradient)

potential_extracted$Strassburg_Scaled = (potential_extracted$Strassburg_India_Clipped - min(potential_extracted$Strassburg_India_Clipped, na.rm= TRUE))/(max(potential_extracted$Strassburg_India_Clipped, na.rm=TRUE) - min(potential_extracted$Strassburg_India_Clipped, na.rm=TRUE))

#since the Strassburg paper has a scale of 0-20, we need to first rescale it to a 0 to 100 and then divide to scale it from 0 to 1

potential_extracted$Strassburg_Scaled_100 <- rescale(potential_extracted$Strassburg_India_Clipped, from = c(0, 20), to = c(0, 100), na,rm=T)

potential_extracted$Strassburg_Scaled_final <- (potential_extracted$Strassburg_Scaled_100/100)

#Rank the districts as per Strassburg
#reorder the districts in descending order of MPI
potential_extracted  <- potential_extracted [order(potential_extracted$Strassburg_Scaled_final, decreasing=TRUE),]

#assign each district a rank
potential_extracted= potential_extracted%>% mutate(strass_rank = match(Strassburg_Scaled_final, unique(Strassburg_Scaled_final)))

#merge the extracted data with districts shapefile

#first remove the districts which don't have a value for climate vulnerability from the larger districts file and potential extracted
districts= districts[!is.na(districts$Pp__M),]

districts_final = sp::merge(districts, potential_extracted[c("strass_rank","Strassburg_India_Clipped", "Strassburg_Scaled_final", "NAME_1", "NAME_2")], by.x = c("NAME_1","NAME_2"), by.y= c("NAME_1", "NAME_2"), duplicateGeoms = T)

writeOGR(districts_final, layer = "districts_final", dsn= "District-MPI-Climate-Pop-Merged-Biophys.shp", driver = "ESRI Shapefile")

#also create a dataframe from the shapefile to use for analysis below 
districts_df_final <- as(districts_final, "data.frame")

write.csv(districts_df_final, "District-Climate-MPI-Biophys-Ranked.csv")

```
